In [1]:
import pandas as pd

In [2]:
url = "data/nhances_2015_2016.csv"
da = pd.read_csv(url)

In [3]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='str')

In [4]:
da['BMXWT'].mean() # we can caluculate mean and it ignore Nan by default

np.float64(81.34267560889516)

In [5]:
da['DMDEDUC2'].unique() # categorical ordered

array([ 5.,  3.,  4.,  2., nan,  1.,  9.])

In [7]:
g = da['RIAGENDR'] # categorical, Unordered [Gender]
g

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64

In [8]:
g.unique()

array([1, 2])

## One Hot Encoding

In [14]:
B = ['bird', 'cat', 'cat', 'dog', 'bird', 'bird']

d = {'categorical': B}

df = pd.DataFrame(d)

In [15]:
df

  categorical
0        bird
1         cat
2         cat
3         dog
4        bird
5        bird

In [16]:
df['categorical']

0    bird
1     cat
2     cat
3     dog
4    bird
5    bird
Name: categorical, dtype: str

In [24]:
# "dummies" is used to create columns corresponding to unique values not comparable
dfDummies = pd.get_dummies(df['categorical'], prefix = 'category')

In [25]:
dfDummies

   category_bird  category_cat  category_dog
0           True         False         False
1          False          True         False
2          False          True         False
3          False         False          True
4           True         False         False
5           True         False         False

In [26]:
dfDummies.values

array([[ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False]])

In [ ]:
# can use dtype= int in get_dummies func to get 1 and 0s vector